### ISSUE TITLE
WeatherStation is created when Field is created

### ISSUE THREAD

**Issue by lKrollo** [Alecsen/SmartFarmer#57]
A weatherstation should automaticly be generated when a user creates a field in the front end. 

In fieldLogic a method should be created that creates a weather staion, and assigns this weather station to the newly created field/mark.

**Comment by Alecsen** [comment]
Did it supringsly fast, all i had to do was 

This method to create a weather station, the values are just zero in the object, because they are automaticly being generated 

![image](https://github.com/Alecsen/SmartFarmer/assets/101325014/397a67bf-0805-4d20-aea7-a0a90fc52d06)

then i just added a line of code to the field logic
![image](https://github.com/Alecsen/SmartFarmer/assets/101325014/5d201c6b-1781-46e4-ad79-d4d13f5a48a5)


This just calls the method and creates the field after the field has been created.
